import type { CountryMeta } from '@/types'

/**
 * Static mapping from ISO 3166-1 numeric codes to alpha-2/alpha-3 codes and names.
 * TopoJSON countries-110m.json uses numeric codes as feature IDs.
 * flagcdn.com uses lowercase alpha-2 codes.
 * Supabase stores alpha-3 codes.
 */
export const COUNTRY_MAP: Record<string, CountryMeta> = {
  '004': { numericCode: '004', alpha2: 'af', alpha3: 'AFG', name: 'Afghanistan' },
  '008': { numericCode: '008', alpha2: 'al', alpha3: 'ALB', name: 'Albania' },
  '012': { numericCode: '012', alpha2: 'dz', alpha3: 'DZA', name: 'Algeria' },
  '024': { numericCode: '024', alpha2: 'ao', alpha3: 'AGO', name: 'Angola' },
  '032': { numericCode: '032', alpha2: 'ar', alpha3: 'ARG', name: 'Argentina' },
  '051': { numericCode: '051', alpha2: 'am', alpha3: 'ARM', name: 'Armenia' },
  '036': { numericCode: '036', alpha2: 'au', alpha3: 'AUS', name: 'Australia' },
  '040': { numericCode: '040', alpha2: 'at', alpha3: 'AUT', name: 'Austria' },
  '031': { numericCode: '031', alpha2: 'az', alpha3: 'AZE', name: 'Azerbaijan' },
  '044': { numericCode: '044', alpha2: 'bs', alpha3: 'BHS', name: 'Bahamas' },
  '050': { numericCode: '050', alpha2: 'bd', alpha3: 'BGD', name: 'Bangladesh' },
  '112': { numericCode: '112', alpha2: 'by', alpha3: 'BLR', name: 'Belarus' },
  '056': { numericCode: '056', alpha2: 'be', alpha3: 'BEL', name: 'Belgium' },
  '084': { numericCode: '084', alpha2: 'bz', alpha3: 'BLZ', name: 'Belize' },
  '204': { numericCode: '204', alpha2: 'bj', alpha3: 'BEN', name: 'Benin' },
  '064': { numericCode: '064', alpha2: 'bt', alpha3: 'BTN', name: 'Bhutan' },
  '068': { numericCode: '068', alpha2: 'bo', alpha3: 'BOL', name: 'Bolivia' },
  '070': { numericCode: '070', alpha2: 'ba', alpha3: 'BIH', name: 'Bosnia and Herzegovina' },
  '072': { numericCode: '072', alpha2: 'bw', alpha3: 'BWA', name: 'Botswana' },
  '076': { numericCode: '076', alpha2: 'br', alpha3: 'BRA', name: 'Brazil' },
  '096': { numericCode: '096', alpha2: 'bn', alpha3: 'BRN', name: 'Brunei' },
  '100': { numericCode: '100', alpha2: 'bg', alpha3: 'BGR', name: 'Bulgaria' },
  '854': { numericCode: '854', alpha2: 'bf', alpha3: 'BFA', name: 'Burkina Faso' },
  '108': { numericCode: '108', alpha2: 'bi', alpha3: 'BDI', name: 'Burundi' },
  '116': { numericCode: '116', alpha2: 'kh', alpha3: 'KHM', name: 'Cambodia' },
  '120': { numericCode: '120', alpha2: 'cm', alpha3: 'CMR', name: 'Cameroon' },
  '124': { numericCode: '124', alpha2: 'ca', alpha3: 'CAN', name: 'Canada' },
  '140': { numericCode: '140', alpha2: 'cf', alpha3: 'CAF', name: 'Central African Republic' },
  '148': { numericCode: '148', alpha2: 'td', alpha3: 'TCD', name: 'Chad' },
  '152': { numericCode: '152', alpha2: 'cl', alpha3: 'CHL', name: 'Chile' },
  '156': { numericCode: '156', alpha2: 'cn', alpha3: 'CHN', name: 'China' },
  '170': { numericCode: '170', alpha2: 'co', alpha3: 'COL', name: 'Colombia' },
  '178': { numericCode: '178', alpha2: 'cg', alpha3: 'COG', name: 'Congo' },
  '180': { numericCode: '180', alpha2: 'cd', alpha3: 'COD', name: 'Democratic Republic of the Congo' },
  '188': { numericCode: '188', alpha2: 'cr', alpha3: 'CRI', name: 'Costa Rica' },
  '384': { numericCode: '384', alpha2: 'ci', alpha3: 'CIV', name: "Côte d'Ivoire" },
  '191': { numericCode: '191', alpha2: 'hr', alpha3: 'HRV', name: 'Croatia' },
  '192': { numericCode: '192', alpha2: 'cu', alpha3: 'CUB', name: 'Cuba' },
  '196': { numericCode: '196', alpha2: 'cy', alpha3: 'CYP', name: 'Cyprus' },
  '203': { numericCode: '203', alpha2: 'cz', alpha3: 'CZE', name: 'Czech Republic' },
  '208': { numericCode: '208', alpha2: 'dk', alpha3: 'DNK', name: 'Denmark' },
  '262': { numericCode: '262', alpha2: 'dj', alpha3: 'DJI', name: 'Djibouti' },
  '214': { numericCode: '214', alpha2: 'do', alpha3: 'DOM', name: 'Dominican Republic' },
  '218': { numericCode: '218', alpha2: 'ec', alpha3: 'ECU', name: 'Ecuador' },
  '818': { numericCode: '818', alpha2: 'eg', alpha3: 'EGY', name: 'Egypt' },
  '222': { numericCode: '222', alpha2: 'sv', alpha3: 'SLV', name: 'El Salvador' },
  '226': { numericCode: '226', alpha2: 'gq', alpha3: 'GNQ', name: 'Equatorial Guinea' },
  '232': { numericCode: '232', alpha2: 'er', alpha3: 'ERI', name: 'Eritrea' },
  '233': { numericCode: '233', alpha2: 'ee', alpha3: 'EST', name: 'Estonia' },
  '748': { numericCode: '748', alpha2: 'sz', alpha3: 'SWZ', name: 'Eswatini' },
  '231': { numericCode: '231', alpha2: 'et', alpha3: 'ETH', name: 'Ethiopia' },
  '238': { numericCode: '238', alpha2: 'fk', alpha3: 'FLK', name: 'Falkland Islands' },
  '242': { numericCode: '242', alpha2: 'fj', alpha3: 'FJI', name: 'Fiji' },
  '246': { numericCode: '246', alpha2: 'fi', alpha3: 'FIN', name: 'Finland' },
  '250': { numericCode: '250', alpha2: 'fr', alpha3: 'FRA', name: 'France' },
  '260': { numericCode: '260', alpha2: 'tf', alpha3: 'ATF', name: 'French Southern Territories' },
  '266': { numericCode: '266', alpha2: 'ga', alpha3: 'GAB', name: 'Gabon' },
  '270': { numericCode: '270', alpha2: 'gm', alpha3: 'GMB', name: 'Gambia' },
  '268': { numericCode: '268', alpha2: 'ge', alpha3: 'GEO', name: 'Georgia' },
  '276': { numericCode: '276', alpha2: 'de', alpha3: 'DEU', name: 'Germany' },
  '288': { numericCode: '288', alpha2: 'gh', alpha3: 'GHA', name: 'Ghana' },
  '300': { numericCode: '300', alpha2: 'gr', alpha3: 'GRC', name: 'Greece' },
  '304': { numericCode: '304', alpha2: 'gl', alpha3: 'GRL', name: 'Greenland' },
  '320': { numericCode: '320', alpha2: 'gt', alpha3: 'GTM', name: 'Guatemala' },
  '324': { numericCode: '324', alpha2: 'gn', alpha3: 'GIN', name: 'Guinea' },
  '624': { numericCode: '624', alpha2: 'gw', alpha3: 'GNB', name: 'Guinea-Bissau' },
  '328': { numericCode: '328', alpha2: 'gy', alpha3: 'GUY', name: 'Guyana' },
  '332': { numericCode: '332', alpha2: 'ht', alpha3: 'HTI', name: 'Haiti' },
  '340': { numericCode: '340', alpha2: 'hn', alpha3: 'HND', name: 'Honduras' },
  '348': { numericCode: '348', alpha2: 'hu', alpha3: 'HUN', name: 'Hungary' },
  '352': { numericCode: '352', alpha2: 'is', alpha3: 'ISL', name: 'Iceland' },
  '356': { numericCode: '356', alpha2: 'in', alpha3: 'IND', name: 'India' },
  '360': { numericCode: '360', alpha2: 'id', alpha3: 'IDN', name: 'Indonesia' },
  '364': { numericCode: '364', alpha2: 'ir', alpha3: 'IRN', name: 'Iran' },
  '368': { numericCode: '368', alpha2: 'iq', alpha3: 'IRQ', name: 'Iraq' },
  '372': { numericCode: '372', alpha2: 'ie', alpha3: 'IRL', name: 'Ireland' },
  '376': { numericCode: '376', alpha2: 'il', alpha3: 'ISR', name: 'Israel' },
  '380': { numericCode: '380', alpha2: 'it', alpha3: 'ITA', name: 'Italy' },
  '388': { numericCode: '388', alpha2: 'jm', alpha3: 'JAM', name: 'Jamaica' },
  '392': { numericCode: '392', alpha2: 'jp', alpha3: 'JPN', name: 'Japan' },
  '400': { numericCode: '400', alpha2: 'jo', alpha3: 'JOR', name: 'Jordan' },
  '398': { numericCode: '398', alpha2: 'kz', alpha3: 'KAZ', name: 'Kazakhstan' },
  '404': { numericCode: '404', alpha2: 'ke', alpha3: 'KEN', name: 'Kenya' },
  '408': { numericCode: '408', alpha2: 'kp', alpha3: 'PRK', name: 'North Korea' },
  '410': { numericCode: '410', alpha2: 'kr', alpha3: 'KOR', name: 'South Korea' },
  '-99': { numericCode: '-99', alpha2: 'xk', alpha3: 'XKX', name: 'Kosovo' },
  '414': { numericCode: '414', alpha2: 'kw', alpha3: 'KWT', name: 'Kuwait' },
  '417': { numericCode: '417', alpha2: 'kg', alpha3: 'KGZ', name: 'Kyrgyzstan' },
  '418': { numericCode: '418', alpha2: 'la', alpha3: 'LAO', name: 'Laos' },
  '428': { numericCode: '428', alpha2: 'lv', alpha3: 'LVA', name: 'Latvia' },
  '422': { numericCode: '422', alpha2: 'lb', alpha3: 'LBN', name: 'Lebanon' },
  '426': { numericCode: '426', alpha2: 'ls', alpha3: 'LSO', name: 'Lesotho' },
  '430': { numericCode: '430', alpha2: 'lr', alpha3: 'LBR', name: 'Liberia' },
  '434': { numericCode: '434', alpha2: 'ly', alpha3: 'LBY', name: 'Libya' },
  '440': { numericCode: '440', alpha2: 'lt', alpha3: 'LTU', name: 'Lithuania' },
  '442': { numericCode: '442', alpha2: 'lu', alpha3: 'LUX', name: 'Luxembourg' },
  '450': { numericCode: '450', alpha2: 'mg', alpha3: 'MDG', name: 'Madagascar' },
  '454': { numericCode: '454', alpha2: 'mw', alpha3: 'MWI', name: 'Malawi' },
  '458': { numericCode: '458', alpha2: 'my', alpha3: 'MYS', name: 'Malaysia' },
  '466': { numericCode: '466', alpha2: 'ml', alpha3: 'MLI', name: 'Mali' },
  '478': { numericCode: '478', alpha2: 'mr', alpha3: 'MRT', name: 'Mauritania' },
  '484': { numericCode: '484', alpha2: 'mx', alpha3: 'MEX', name: 'Mexico' },
  '498': { numericCode: '498', alpha2: 'md', alpha3: 'MDA', name: 'Moldova' },
  '496': { numericCode: '496', alpha2: 'mn', alpha3: 'MNG', name: 'Mongolia' },
  '499': { numericCode: '499', alpha2: 'me', alpha3: 'MNE', name: 'Montenegro' },
  '504': { numericCode: '504', alpha2: 'ma', alpha3: 'MAR', name: 'Morocco' },
  '508': { numericCode: '508', alpha2: 'mz', alpha3: 'MOZ', name: 'Mozambique' },
  '104': { numericCode: '104', alpha2: 'mm', alpha3: 'MMR', name: 'Myanmar' },
  '516': { numericCode: '516', alpha2: 'na', alpha3: 'NAM', name: 'Namibia' },
  '524': { numericCode: '524', alpha2: 'np', alpha3: 'NPL', name: 'Nepal' },
  '528': { numericCode: '528', alpha2: 'nl', alpha3: 'NLD', name: 'Netherlands' },
  '540': { numericCode: '540', alpha2: 'nc', alpha3: 'NCL', name: 'New Caledonia' },
  '554': { numericCode: '554', alpha2: 'nz', alpha3: 'NZL', name: 'New Zealand' },
  '558': { numericCode: '558', alpha2: 'ni', alpha3: 'NIC', name: 'Nicaragua' },
  '562': { numericCode: '562', alpha2: 'ne', alpha3: 'NER', name: 'Niger' },
  '566': { numericCode: '566', alpha2: 'ng', alpha3: 'NGA', name: 'Nigeria' },
  '807': { numericCode: '807', alpha2: 'mk', alpha3: 'MKD', name: 'North Macedonia' },
  '578': { numericCode: '578', alpha2: 'no', alpha3: 'NOR', name: 'Norway' },
  '512': { numericCode: '512', alpha2: 'om', alpha3: 'OMN', name: 'Oman' },
  '586': { numericCode: '586', alpha2: 'pk', alpha3: 'PAK', name: 'Pakistan' },
  '275': { numericCode: '275', alpha2: 'ps', alpha3: 'PSE', name: 'Palestine' },
  '591': { numericCode: '591', alpha2: 'pa', alpha3: 'PAN', name: 'Panama' },
  '598': { numericCode: '598', alpha2: 'pg', alpha3: 'PNG', name: 'Papua New Guinea' },
  '600': { numericCode: '600', alpha2: 'py', alpha3: 'PRY', name: 'Paraguay' },
  '604': { numericCode: '604', alpha2: 'pe', alpha3: 'PER', name: 'Peru' },
  '608': { numericCode: '608', alpha2: 'ph', alpha3: 'PHL', name: 'Philippines' },
  '616': { numericCode: '616', alpha2: 'pl', alpha3: 'POL', name: 'Poland' },
  '620': { numericCode: '620', alpha2: 'pt', alpha3: 'PRT', name: 'Portugal' },
  '630': { numericCode: '630', alpha2: 'pr', alpha3: 'PRI', name: 'Puerto Rico' },
  '634': { numericCode: '634', alpha2: 'qa', alpha3: 'QAT', name: 'Qatar' },
  '642': { numericCode: '642', alpha2: 'ro', alpha3: 'ROU', name: 'Romania' },
  '643': { numericCode: '643', alpha2: 'ru', alpha3: 'RUS', name: 'Russia' },
  '646': { numericCode: '646', alpha2: 'rw', alpha3: 'RWA', name: 'Rwanda' },
  '682': { numericCode: '682', alpha2: 'sa', alpha3: 'SAU', name: 'Saudi Arabia' },
  '686': { numericCode: '686', alpha2: 'sn', alpha3: 'SEN', name: 'Senegal' },
  '688': { numericCode: '688', alpha2: 'rs', alpha3: 'SRB', name: 'Serbia' },
  '694': { numericCode: '694', alpha2: 'sl', alpha3: 'SLE', name: 'Sierra Leone' },
  '703': { numericCode: '703', alpha2: 'sk', alpha3: 'SVK', name: 'Slovakia' },
  '705': { numericCode: '705', alpha2: 'si', alpha3: 'SVN', name: 'Slovenia' },
  '090': { numericCode: '090', alpha2: 'sb', alpha3: 'SLB', name: 'Solomon Islands' },
  '706': { numericCode: '706', alpha2: 'so', alpha3: 'SOM', name: 'Somalia' },
  '710': { numericCode: '710', alpha2: 'za', alpha3: 'ZAF', name: 'South Africa' },
  '728': { numericCode: '728', alpha2: 'ss', alpha3: 'SSD', name: 'South Sudan' },
  '724': { numericCode: '724', alpha2: 'es', alpha3: 'ESP', name: 'Spain' },
  '144': { numericCode: '144', alpha2: 'lk', alpha3: 'LKA', name: 'Sri Lanka' },
  '729': { numericCode: '729', alpha2: 'sd', alpha3: 'SDN', name: 'Sudan' },
  '740': { numericCode: '740', alpha2: 'sr', alpha3: 'SUR', name: 'Suriname' },
  '752': { numericCode: '752', alpha2: 'se', alpha3: 'SWE', name: 'Sweden' },
  '756': { numericCode: '756', alpha2: 'ch', alpha3: 'CHE', name: 'Switzerland' },
  '760': { numericCode: '760', alpha2: 'sy', alpha3: 'SYR', name: 'Syria' },
  '158': { numericCode: '158', alpha2: 'tw', alpha3: 'TWN', name: 'Taiwan' },
  '762': { numericCode: '762', alpha2: 'tj', alpha3: 'TJK', name: 'Tajikistan' },
  '834': { numericCode: '834', alpha2: 'tz', alpha3: 'TZA', name: 'Tanzania' },
  '764': { numericCode: '764', alpha2: 'th', alpha3: 'THA', name: 'Thailand' },
  '626': { numericCode: '626', alpha2: 'tl', alpha3: 'TLS', name: 'Timor-Leste' },
  '768': { numericCode: '768', alpha2: 'tg', alpha3: 'TGO', name: 'Togo' },
  '780': { numericCode: '780', alpha2: 'tt', alpha3: 'TTO', name: 'Trinidad and Tobago' },
  '788': { numericCode: '788', alpha2: 'tn', alpha3: 'TUN', name: 'Tunisia' },
  '792': { numericCode: '792', alpha2: 'tr', alpha3: 'TUR', name: 'Turkey' },
  '795': { numericCode: '795', alpha2: 'tm', alpha3: 'TKM', name: 'Turkmenistan' },
  '800': { numericCode: '800', alpha2: 'ug', alpha3: 'UGA', name: 'Uganda' },
  '804': { numericCode: '804', alpha2: 'ua', alpha3: 'UKR', name: 'Ukraine' },
  '784': { numericCode: '784', alpha2: 'ae', alpha3: 'ARE', name: 'United Arab Emirates' },
  '826': { numericCode: '826', alpha2: 'gb', alpha3: 'GBR', name: 'United Kingdom' },
  '840': { numericCode: '840', alpha2: 'us', alpha3: 'USA', name: 'United States' },
  '858': { numericCode: '858', alpha2: 'uy', alpha3: 'URY', name: 'Uruguay' },
  '860': { numericCode: '860', alpha2: 'uz', alpha3: 'UZB', name: 'Uzbekistan' },
  '548': { numericCode: '548', alpha2: 'vu', alpha3: 'VUT', name: 'Vanuatu' },
  '862': { numericCode: '862', alpha2: 've', alpha3: 'VEN', name: 'Venezuela' },
  '704': { numericCode: '704', alpha2: 'vn', alpha3: 'VNM', name: 'Vietnam' },
  '732': { numericCode: '732', alpha2: 'eh', alpha3: 'ESH', name: 'Western Sahara' },
  '887': { numericCode: '887', alpha2: 'ye', alpha3: 'YEM', name: 'Yemen' },
  '894': { numericCode: '894', alpha2: 'zm', alpha3: 'ZMB', name: 'Zambia' },
  '716': { numericCode: '716', alpha2: 'zw', alpha3: 'ZWE', name: 'Zimbabwe' },
}

export function getCountryByNumericCode(numericCode: string): CountryMeta | undefined {
  return COUNTRY_MAP[numericCode]
}

export function getAlpha2(numericCode: string): string | undefined {
  return COUNTRY_MAP[numericCode]?.alpha2
}

export function getAlpha3(numericCode: string): string | undefined {
  return COUNTRY_MAP[numericCode]?.alpha3
}

export function getCountryName(numericCode: string): string {
  return COUNTRY_MAP[numericCode]?.name || 'Unknown'
}

export function getCountryByAlpha3(alpha3: string): CountryMeta | undefined {
  return Object.values(COUNTRY_MAP).find((c) => c.alpha3 === alpha3)
}

export function numericCodeFromAlpha3(alpha3: string): string | undefined {
  return Object.values(COUNTRY_MAP).find((c) => c.alpha3 === alpha3)?.numericCode
}

export function getFlagUrl(alpha2: string): string {
  // Use SVG flags for infinite scalability - stays crisp at any zoom level
  return `https://flagcdn.com/${alpha2.toLowerCase()}.svg`
}

export const TOTAL_COUNTRIES = Object.keys(COUNTRY_MAP).length
